version: '3.8'

x-stream-common:
  &stream-common
  image: invest_bot:latest
  build:
    context: ..
    dockerfile: docker/Dockerfile
  volumes:
    - ../scripts:/app/scripts
    - ../src:/app/src
  depends_on:
    &stream-common-depends-on
    postgres-db:
      condition: service_healthy
    kafka:
      condition: service_healthy


services:
  zookeeper:
    image: zookeeper:3.9.4
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: apache/kafka:4.1.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9093:9093" # controller listener
    environment:
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    healthcheck:
      test: [ "CMD", "bash", "nc -z localhost 9092" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    networks:
      - kafka-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    ports:
      - "8080:8080"
    networks:
      - kafka-net

  producer_tbank_stream_candles_1min:
    <<: *stream-common
    command: python scripts/produce_stream_candles_1_min.py
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8000/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s # Optional: initial delay before starting health checks
    restart: always
    depends_on:
      <<: *stream-common-depends-on

  consumer_tbank_stream_candles_1min:
    <<: *stream-common
    command: python scripts/consume_stream_candles_1_min.py
    depends_on:
      <<: *stream-common-depends-on

networks:
  kafka-net:
    driver: bridge

volumes:
  invest_bot_postgres:
    external: true
